import type { Config } from "tailwindcss"

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        segoe: ["Segoe UI", "Tahoma", "Geneva", "Verdana", "sans-serif"],
      },
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: {
            height: "0",
          },
          to: {
            height: "var(--radix-accordion-content-height)",
          },
        },
        "accordion-up": {
          from: {
            height: "var(--radix-accordion-content-height)",
          },
          to: {
            height: "0",
          },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-10px)" },
        },
        glow: {
          "0%, 100%": { boxShadow: "0 0 5px rgba(59, 130, 246, 0.5)" },
          "50%": { boxShadow: "0 0 20px rgba(59, 130, 246, 0.8)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        float: "float 3s ease-in-out infinite",
        glow: "glow 2s ease-in-out infinite alternate",
      },
      backdropBlur: {
        xs: "2px",
      },
    },
  },
  plugins: [],
  safelist: [
    // Color classes for dynamic content
    "from-blue-50",
    "to-blue-50",
    "border-blue-200",
    "from-blue-500",
    "to-blue-600",
    "from-green-50",
    "to-green-50",
    "border-green-200",
    "from-green-500",
    "to-green-600",
    "from-purple-50",
    "to-purple-50",
    "border-purple-200",
    "from-purple-500",
    "to-purple-600",
    "from-orange-50",
    "to-orange-50",
    "border-orange-200",
    "from-orange-500",
    "to-orange-600",
    "from-cyan-50",
    "to-cyan-50",
    "border-cyan-200",
    "from-cyan-500",
    "to-cyan-600",
    "from-pink-50",
    "to-pink-50",
    "border-pink-200",
    "from-pink-500",
    "to-pink-600",
    "from-indigo-50",
    "to-indigo-50",
    "border-indigo-200",
    "from-indigo-500",
    "to-indigo-600",
    "from-violet-50",
    "to-violet-50",
    "border-violet-200",
    "from-violet-500",
    "to-violet-600",
    "from-fuchsia-50",
    "to-fuchsia-50",
    "border-fuchsia-200",
    "from-fuchsia-500",
    "to-fuchsia-600",
    "from-teal-50",
    "to-teal-50",
    "border-teal-200",
    "from-teal-500",
    "to-teal-600",
    "from-emerald-50",
    "to-emerald-50",
    "border-emerald-200",
    "from-emerald-500",
    "to-emerald-600",
    "bg-blue-500",
    "bg-green-500",
    "bg-purple-500",
    "bg-orange-500",
    "bg-cyan-500",
    "bg-pink-500",
    "text-blue-600",
    "text-green-600",
    "text-purple-600",
    "text-orange-600",
    "text-cyan-600",
    "text-pink-600",
  ],
}
export default config
